# Generated by Django 3.0.3 on 2020-02-18 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loka', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='create_date',
            new_name='created_date',
        ),
    ]
